### ISSUE TITLE
Need FOR the dataset

### ISSUE THREAD

**Issue by Lireanstar** [Emmonss/EmotionalConversationDataSet#1]

**Comment by Lireanstar** [comment]
How can i get in thoch with you? e-mail seems no-one-answer

**Comment by Emmonss** [comment]
this dataset is a part of lab's private dataset。 I was graduated so that i can not give it to you。you can get in touch with my ex-tutor with email sunx@hfut.edu.cn。that may helpful。

**Comment by Emmonss** [comment]
this dataset is a part of lab's private dataset。 I was graduated so that i can not give it to you。you can get in touch with my ex-tutor with email sunx@hfut.edu.cn。that may helpful。

**Comment by Emmonss** [comment]
this dataset is a part of lab's private dataset。 I was graduated so that i can not give it to you。you can get in touch with my ex-tutor with email sunx@hfut.edu.cn。that may helpful。
